# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Cron Task

on:
  schedule:
    - cron: "15 0/12 * * *"

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11.2"
      #         cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip requests==2.28.2 beautifulsoup4==4.11.2 lxml==4.9.2

      - name: Build index
        run: |
          python ph.py > ph_data.json
          mkdir -p tmp
          mv data tmp
          mv ph_data.json tmp

      - uses: actions/checkout@v3
        with:
          ref: release
          clean: false
      - name: Git push assets to "release" branch
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          mv tmp/ph_data.json .
          cp --force --archive --update --link tmp/data .
          rm -rf tmp
          git add -f ph_data.json data/*
          git commit -m "$(date +%Y%m%d%H%M)"
          git push -f -u origin release
